### ISSUE TITLE
on initial load, ad label should be "Sponsored"

### ISSUE THREAD

**Issue by dws122** [maithemewp/mai-publisher#1]
current blank on first plugin load

**Comment by JiveDig** [comment]
Hmmm, I have some code doing this if first-version option is not set. Must not be working. 

https://github.com/maithemewp/mai-publisher/blob/develop/classes/class-upgrade.php#L42

**Comment by JiveDig** [comment]
Should be fixed in https://github.com/maithemewp/mai-publisher/commit/4e0b738e02cff4b750a4aadc03aadad5ea193803
