### ISSUE TITLE
In recipe ads overlap ingredients (on Safari at least)

### ISSUE THREAD

**Issue by JiveDig** [maithemewp/mai-publisher#10]
I think this is aspect-ratio plus max-width related. Similar bug a few weeks ago, argh.

**Comment by dws122** [comment]
It would be nice to only use the 600 pixel high ad if the content block had significant content in it to support it

**Comment by JiveDig** [comment]
This was fixed when we bailed on aspect-ratio and went for the older padding-bottom trick for aspect ratio. It's been solid since.
