### ISSUE TITLE
display location of "Before Entry Content" does not show mai-ad-video-tdih

### ISSUE THREAD

**Issue by dws122** [maithemewp/mai-publisher#11]
tested on two sites, CM and SugarMakers

when selecting Before Entry Content, the video ad will not show.

<img width="484" alt="Screenshot 2023-12-16 at 8 06 25 AM" src="https://github.com/maithemewp/mai-publisher/assets/12969150/d48dc8cf-f542-4f22-a6c5-b8ac269101f6">

**Comment by dws122** [comment]
additionally, the position of In Content After Elements 0 doesn't display the ads location.

consequently, you can't position an ad right after the title, or right before it.

<img width="549" alt="Screenshot 2023-12-16 at 8 09 53 AM" src="https://github.com/maithemewp/mai-publisher/assets/12969150/4dbf1ba8-aba3-4bad-ae1b-80f94181ec3b">

**Comment by JiveDig** [comment]
I can't believe it, but the fix was width: 100%;, likely cause it's a flex item. Wow. 

Fixed via https://github.com/maithemewp/mai-publisher/commit/f1d247184b8db39fb593a55d62bf8a7e593c1c91
