### ISSUE TITLE
unable to select Top Level Category for IAB Category

### ISSUE THREAD

**Issue by dws122** [maithemewp/mai-publisher#3]
when selecting top level, and saving, it reverts to no entry.

<img width="847" alt="Screenshot 2023-10-05 at 12 15 28 PM" src="https://github.com/maithemewp/mai-publisher/assets/12969150/bee59b08-851a-4e9c-8709-f2d4f8dfe1a5">

I think we should be able to save the top level category as the site category.

**Comment by JiveDig** [comment]
Weird my testing worked for this. I'll look into it. Were you trying Entertainment? Did it happen with multiple top level?

**Comment by dws122** [comment]
tested on multiple sites.  works with Healthy Living, Automotive.

Does NOT work for Entertainment on tested sites.

**Comment by JiveDig** [comment]
Well, TIL that `sanitize_key` _also_ forces letters to lowercase. So `JLBCU7` was being sanitized to `jlbcu7`. The only ones that are failing are the few categories that are non-numeric values (for whatever reason they did it that way). Fix coming.

**Comment by JiveDig** [comment]
Also noting that I'm switching to `sanitize_text_field()`.
